#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_CAM_CAL_HI551QTECHV2_SUPPORT)				+= hi551qtechv2_eeprom.o
