
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_MPU6515A),y)
obj-y	+=  mpu6515/
endif

ifeq ($(CONFIG_MTK_BMA222E_NEW),y)
obj-y	+=  bma222E-new/
endif

ifeq ($(CONFIG_MTK_BMA222E_AIO),y)
obj-y	+=  bma222E-aio/
endif

