/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Written by: daniel_hk (https://github.com/danielhk)
 ** 2016/10/12: initial release
 */
#ifndef AUDDRV_TFA9897_H
#define AUDDRV_TFA9897_H

#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/init.h>
#include <linux/slab.h>
#include <linux/fs.h>
#include <linux/delay.h>
#include <linux/vmalloc.h>
#include <linux/sched.h>
#include <linux/spinlock.h>
#include <linux/jiffies.h>
#include <linux/string.h>
#include <asm/div64.h>
#include <asm/io.h>
// MTK headers
#include <mach/eint.h>
#include <mach/mt_irq.h>
#include <mach/mt_reg_base.h>
#include <mach/mt_typedefs.h>
#include <linux/aee.h>
#include <mach/mt_gpio.h>
#include <mach/mt_boot.h>
// generated by codegen
#include <cust_eint.h>
#include <cust_gpio_usage.h>

#ifndef I2C_SLAVE
#define I2C_SLAVE		0x0703
#define I2C_SLAVE_FORCE		0x0706
#endif

// Log define
#define NXP_INFO(fmt,arg...)    printk("<<-NXP-INFO->> "fmt"\n",##arg)
#define NXP_ERROR(fmt,arg...)   printk("<<-NXP-ERROR->> "fmt"\n",##arg)

// Error no.
#define ERROR_NO_FILE		2   //ENOENT
#define ERROR_FILE_READ		23  //ENFILE
#define ERROR_FILE_TYPE		21  //EISDIR
#define ERROR_GPIO_REQUEST	4   //EINTR
#define ERROR_I2C_TRANSFER	5   //EIO
#define ERROR_NO_RESPONSE	16  //EBUSY
#define ERROR_TIMEOUT		110 //ETIMEDOUT

#endif


